### ISSUE TITLE
Vim syntax highlighter for spl

### ISSUE THREAD

**Issue by convict-git** [eXpOSNitc/spl#1]
I wrote a syntax highlighter vimscript file for spl. Please let me know if it qualifies for a PR. 

Attaching screenshot (used with [PaperColor theme) ](https://github.com/NLKNguyen/papercolor-theme).
![Screenshot from 2020-01-29 22-02-56](https://user-images.githubusercontent.com/34399448/73376391-63f17780-42e3-11ea-8e89-caad62c44566.png)
![Screenshot from 2020-01-29 22-03-18](https://user-images.githubusercontent.com/34399448/73376394-63f17780-42e3-11ea-833c-57e6c9fcf556.png)
![Screenshot from 2020-01-29 22-03-29](https://user-images.githubusercontent.com/34399448/73376397-648a0e00-42e3-11ea-95c1-1bfcb24bdf89.png)
![Screenshot from 2020-01-29 22-03-53](https://user-images.githubusercontent.com/34399448/73376403-65bb3b00-42e3-11ea-8713-0686b527c3e5.png)

**Comment by itsfarseen** [comment]
Hi @convict-git. Awesome job!
However, this repo is limited to the code for actual compiler code.
We have recently created a place where you can upload your work: https://exposnitc.github.io/user-contrib/
Read the instructions there and please upload this there. This will be really useful for future students.
